[package]
name = "kafka_producer"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = { version = "0.29", features = ["cmake-build"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
